### ISSUE TITLE
CT: audio decode failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#201]
```
resistance-in-a-wire : accessibility-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544591141582:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544609826828:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544627492654:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544591141582:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544609826828:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544627492654:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544590333657:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544603420314:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544628463838:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544590333657:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544603420314:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : accessibility-fuzzBoard : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544628463838:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : build : phet
Failure to grunt snapshot-1544587309442/resistance-in-a-wire:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (resistance-in-a-wire, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1544587309442/tambo/js/../sounds/bright-marimba-short.mp3'
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1544587309442/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : build : phet-io
Failure to grunt snapshot-1544587309442-phet-io/resistance-in-a-wire:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (resistance-in-a-wire, brands: phet, phet-io)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/tambo/js/../sounds/bright-marimba-short.mp3'
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1544587309442-phet-io/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544590368921:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544601998070:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544622724070:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544590368921:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544601998070:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544622724070:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544598743607:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544606655786:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544626613930:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544598743607:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544606655786:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544626613930:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544601269106:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544609308466:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544619784062:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544601269106:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544609308466:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544619784062:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544594308469:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544614250114:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : load
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544623896872:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544594308469:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544614250114:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
resistance-in-a-wire : xss-fuzz : run
Uncaught Error: Assertion failed: audio decode failed
Error: Assertion failed: audio decode failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/assert/js/assert.js:22:13)
    at AudioContext.SoundClip.soundInfoDecoder.decode (https://bayes.colorado.edu/continuous-testing/snapshot-1544587309442/tambo/js/sound-generators/SoundClip.js?bust=1544623896872:94:19)
id: Bayes Chrome
Approximately 12/11/2018, 9:01:49 PM
```

**Comment by jbphet** [comment]
I think this was due to a new sound file that I'd failed to commit.  I've done so now, and will keep an eye on CT to see if this resolves the issue.

**Comment by jbphet** [comment]
Three iterations of CT have succeeded since the sound file was committed, looks like the problem is solved, closing.
