### ISSUE TITLE
CT: Accessible section must have a label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/resistance-in-a-wire#214]
Lots of errors for this sim in CT, see below.  

Most of these appear to be related to a11y:
> Accessible section must have a label

```
resistance-in-a-wire : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: t.replace is not a function
TypeError: t.replace is not a function
at Ai (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:301711)
at Object.setTextContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:303042)
at Ni.setLabelSiblingContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:313535)
at Ni.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:307806)
at Wi.initializeAccessibleInstance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:316870)
at new Wi (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:316101)
at Function.createFromPool (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:84996)
at Object.createTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:323544)
at Object.createTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:323666)
at Object.createTree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/build/phet-io/resistance-in-a-wire_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866383938%7D&fuzz&memoryLimit=1000&phetioStandalone:904:323666)
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : interactive-description-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/resistance-in-a-wire_en.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22interactive-description-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588865170833%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : interactive-description-fuzzBoard : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/resistance-in-a-wire_en.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22interactive-description-fuzzBoard%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866310326%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/resistance-in-a-wire_en.html?continuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22phet-io-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588865455322%7D&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-mirror-inputs-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/mirror-inputs/?sim=resistance-in-a-wire&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588865199446%7D
Uncaught Error: Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-state-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/state/?sim=resistance-in-a-wire&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22phet-io-state-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588865154415%7D
Uncaught Error: Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-studio-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/studio/?sim=resistance-in-a-wire&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22resistance-in-a-wire%22%2C%22phet-io-studio-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588865479647%7D
Uncaught Error: Uncaught Error: Assertion failed: Accessible section must have a label
Error: Assertion failed: Accessible section must have a label
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new AccessibleSectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/scenery-phet/js/accessibility/AccessibleSectionNode.js:23:13)
at new ResistanceInAWireScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireScreenView.js:32:27)
at ResistanceInAWireScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/resistance-in-a-wire/js/resistance-in-a-wire/ResistanceInAWireScreen.js:24:32)
at ResistanceInAWireScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:808:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/joist/js/Sim.js:827:25
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/phet-io-wrappers-tests.html?sim=resistance-in-a-wire&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: resistance-in-a-wire: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Accessible section must have a label
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/js/tests/SimTests.js:321

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM

----------------------------------

resistance-in-a-wire : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/phet-io-wrappers-tests.html?sim=resistance-in-a-wire
3 out of 4 tests passed. 1 failed.
SimTests: resistance-in-a-wire: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Accessible section must have a label
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/phet-io-wrappers/js/tests/SimTests.js:321

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM
```

**Comment by zepumph** [comment]
I renamed the file also, but really the bug was that I was accidentally exporting the superType after the inherit call, instead of the subtype. Closing
